#!/usr/bin/env python3
"""Assemble the IMSAI Monitor V5.6 two-page ROM from its Z80 source.

The checked-in source is intentionally close to the historical SLR Z80ASM
syntax used by the original monitor. Ubuntu's z80asm is stricter in a few
places. This program performs syntax-only normalization, assembles each 4K
ROM page with the real z80asm assembler, pads each page to exactly 4096 bytes,
and joins the pages into the 8192-byte 27C64/28C64 programming image.

No machine-code bytes are generated by this script: z80asm is the assembler.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import shutil
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "IMSAI_MONITOR_V5.6_TARGET_MERGED.z80"
ROM_BASE = 0xF000
PAGE_SIZE = 4096
COMBINED_SIZE = PAGE_SIZE * 2

LOW_NAME = "IMSAI_MONITOR_V5.6_TARGET_LOW_4K.BIN"
HIGH_NAME = "IMSAI_MONITOR_V5.6_TARGET_HIGH_4K.BIN"
COMBINED_NAME = "IMSAI_MONITOR_V5.6_TARGET_28C64_8K.BIN"
HEX_NAME = "IMSAI_MONITOR_V5.6_TARGET_28C64_8K.HEX"
SUMS_NAME = "SHA256SUMS.txt"

OPCODES = {
    "ADC", "ADD", "AND", "BIT", "CALL", "CCF", "CP", "CPD", "CPDR",
    "CPI", "CPIR", "CPL", "DAA", "DEC", "DI", "DJNZ", "EI", "EX",
    "EXX", "HALT", "IM", "IN", "INC", "IND", "INDR", "INI", "INIR",
    "JP", "JR", "LD", "LDD", "LDDR", "LDI", "LDIR", "NEG", "NOP",
    "OR", "OTDR", "OTIR", "OUT", "OUTD", "OUTI", "POP", "PUSH",
    "RES", "RET", "RETI", "RETN", "RL", "RLA", "RLC", "RLCA", "RLD",
    "RR", "RRA", "RRC", "RRCA", "RRD", "RST", "SBC", "SCF", "SET",
    "SLA", "SLL", "SRA", "SRL", "SUB", "XOR",
}
DIRECTIVES = {
    "DB", "DEFB", "DW", "DEFW", "DS", "DEFS", "EQU", "IF", "ELSE",
    "ENDIF", "END", "ORG", "INCLUDE", "INCBIN", "SEEK",
}
FIRST_TOKENS = OPCODES | DIRECTIVES


def split_comment(line: str) -> tuple[str, str]:
    """Split a source line at a semicolon that is not inside quotes."""
    quote: str | None = None
    escaped = False
    for index, ch in enumerate(line):
        if quote is not None:
            if escaped:
                escaped = False
            elif ch == "\\":
                escaped = True
            elif ch == quote:
                quote = None
        elif ch in "'\"":
            quote = ch
        elif ch == ";":
            return line[:index], line[index:]
    return line, ""


def transform_unquoted(text: str, transform) -> str:
    """Apply transform only to text outside single- or double-quoted strings."""
    result: list[str] = []
    start = 0
    index = 0
    while index < len(text):
        if text[index] not in "'\"":
            index += 1
            continue
        if start < index:
            result.append(transform(text[start:index]))
        quote = text[index]
        qstart = index
        index += 1
        escaped = False
        while index < len(text):
            ch = text[index]
            if escaped:
                escaped = False
            elif ch == "\\":
                escaped = True
            elif ch == quote:
                index += 1
                break
            index += 1
        result.append(text[qstart:index])
        start = index
    if start < len(text):
        result.append(transform(text[start:]))
    return "".join(result)


def insert_missing_db_commas(code: str) -> str:
    """Fix historical constructs such as: DB 'Menu Error'CR,LF."""
    if not re.search(r"\b(?:DB|DEFB)\b", code, flags=re.IGNORECASE):
        return code

    out: list[str] = []
    index = 0
    while index < len(code):
        ch = code[index]
        out.append(ch)
        if ch not in "'\"":
            index += 1
            continue

        quote = ch
        index += 1
        escaped = False
        while index < len(code):
            ch = code[index]
            out.append(ch)
            index += 1
            if escaped:
                escaped = False
            elif ch == "\\":
                escaped = True
            elif ch == quote:
                break

        look = index
        while look < len(code) and code[look] in " \t":
            look += 1
        if look < len(code) and (code[look].isalpha() or code[look] == "_"):
            out.append(",")
    return "".join(out)


def normalize_unquoted_segment(segment: str) -> str:
    # SLR treats identifiers case-insensitively; stock Ubuntu z80asm does not.
    segment = segment.upper()

    # z80asm identifiers cannot end in '$'. Preserve the semantic name.
    segment = re.sub(
        r"(?<![A-Z0-9_])([A-Z_][A-Z0-9_]*)\$(?![A-Z0-9_])",
        r"\1_DOLLAR",
        segment,
    )

    # SLR expression/operator spelling.
    segment = re.sub(r"\bNOT\b", "~", segment)

    # SLR accepts explicit accumulator forms that z80asm spells with one
    # operand for these instructions.
    segment = re.sub(r"\b(AND|OR|XOR|CP)\s+A\s*,\s*", r"\1 ", segment)

    # SLR also accepts ADD <expr> as shorthand for ADD A,<expr>.
    segment = re.sub(
        r"\bADD\s+(?!A\s*,|HL\s*,|IX\s*,|IY\s*,)([A-Z0-9_+\-~]+)",
        r"ADD A,\1",
        segment,
    )

    # Immediate-port I/O requires parentheses in Ubuntu z80asm.
    segment = re.sub(
        r"\bIN\s+A\s*,\s*(?!\()([A-Z0-9_+\-~]+)",
        r"IN A,(\1)",
        segment,
    )
    segment = re.sub(
        r"\bOUT\s+(?!\()([A-Z0-9_+\-~]+)\s*,\s*A\b",
        r"OUT (\1),A",
        segment,
    )
    return segment


def add_label_colon(code: str) -> str:
    """Convert SLR's optional-colon labels to z80asm label syntax."""
    match = re.match(
        r"^(\s*)([A-Z_][A-Z0-9_]*)(\s+)([A-Z][A-Z0-9_]*)\b",
        code,
    )
    if not match:
        return code
    first = match.group(2)
    second = match.group(4)
    if first in FIRST_TOKENS or second not in FIRST_TOKENS:
        return code
    insert_at = match.start(3)
    return code[:insert_at] + ":" + code[insert_at:]


def extract_rom_page(source: str, page: int) -> list[str]:
    """Select the top-level ROM_PAGE branch while retaining nested conditionals."""
    lines = source.splitlines()
    outer_if = None
    outer_else = None
    outer_endif = None
    depth = 0

    for idx, line in enumerate(lines):
        code, _ = split_comment(line)
        token = code.strip().upper()
        if outer_if is None:
            if re.fullmatch(r"IF\s+ROM_PAGE", token):
                outer_if = idx
                depth = 1
            continue

        if re.match(r"^IF\b", token):
            depth += 1
        elif token == "ENDIF":
            depth -= 1
            if depth == 0:
                outer_endif = idx
                break
        elif token == "ELSE" and depth == 1:
            outer_else = idx

    if outer_if is None or outer_else is None or outer_endif is None:
        raise RuntimeError("Could not locate the top-level IF ROM_PAGE / ELSE / ENDIF")

    if page == 1:
        selected = lines[outer_if + 1 : outer_else]
    else:
        selected = lines[outer_else + 1 : outer_endif]

    # The source's final END is outside the ROM_PAGE IF. Add one explicitly.
    return selected + ["", "\tEND"]


def normalize_page(lines: list[str]) -> str:
    normalized: list[str] = []
    seen_org = False

    for raw in lines:
        code, comment = split_comment(raw)
        code = insert_missing_db_commas(code)
        code = transform_unquoted(code, normalize_unquoted_segment)
        code = add_label_colon(code)

        org = re.match(r"^(\s*)ORG\s+(.+?)\s*$", code, flags=re.IGNORECASE)
        if org:
            if not seen_org:
                seen_org = True
            else:
                # z80asm changes its PC on ORG but does not put padding in the
                # output file. DEFS makes the physical ROM holes explicit.
                code = f"{org.group(1)}DEFS {org.group(2)}-$,0"

        normalized.append(code + comment)

    if not seen_org:
        raise RuntimeError("Selected ROM page contains no ORG directive")
    return "\n".join(normalized) + "\n"


def run_assembler(assembler: str, source: Path, output: Path, listing: Path, labels: Path) -> None:
    command = [
        assembler,
        f"--output={output}",
        f"--list={listing}",
        f"--label={labels}",
        str(source),
    ]
    try:
        completed = subprocess.run(command, text=True, capture_output=True, check=False)
    except FileNotFoundError as exc:
        raise RuntimeError(
            f"Assembler '{assembler}' not found. On Ubuntu install it with: "
            "sudo apt install z80asm"
        ) from exc

    if completed.returncode != 0:
        detail = "\n".join(part for part in (completed.stdout, completed.stderr) if part.strip())
        raise RuntimeError(
            f"z80asm failed for {source.name} (exit {completed.returncode})\n{detail}"
        )


def assemble_page(page: int, assembler: str, build_dir: Path) -> bytes:
    tag = "HIGH" if page else "LOW"
    selected = extract_rom_page(SOURCE.read_text(encoding="latin-1"), page)
    strict_source = normalize_page(selected)

    asm_path = build_dir / f"IMSAI_MONITOR_V5.6_TARGET_{tag}_4K.z80asm.asm"
    raw_path = build_dir / f".{tag.lower()}-raw.bin"
    list_path = build_dir / f"IMSAI_MONITOR_V5.6_TARGET_{tag}_4K.lst"
    label_path = build_dir / f"IMSAI_MONITOR_V5.6_TARGET_{tag}_4K.labels"
    # Keep the source's legacy one-byte encoding in comments. The assembler
    # ignores comments, but latin-1 lets us preserve the file losslessly.
    asm_path.write_text(strict_source, encoding="latin-1")

    run_assembler(assembler, asm_path, raw_path, list_path, label_path)
    data = raw_path.read_bytes()
    raw_path.unlink(missing_ok=True)

    if len(data) > PAGE_SIZE:
        raise RuntimeError(
            f"{tag} page assembled to {len(data)} bytes; it exceeds the 4096-byte ROM bank"
        )
    return data.ljust(PAGE_SIZE, b"\x00")


def intel_hex(data: bytes, width: int = 16) -> str:
    records: list[str] = []
    for address in range(0, len(data), width):
        chunk = data[address : address + width]
        record = bytearray((len(chunk), (address >> 8) & 0xFF, address & 0xFF, 0))
        record.extend(chunk)
        checksum = (-sum(record)) & 0xFF
        records.append(":" + bytes(record + bytes((checksum,))).hex().upper())
    records.append(":00000001FF")
    return "\n".join(records) + "\n"


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def compare_reference(name: str, generated: bytes, reference: bytes, page_base: int | None) -> None:
    if generated == reference:
        print(f"  reference match: {name}")
        return

    diffs = [idx for idx, pair in enumerate(zip(generated, reference)) if pair[0] != pair[1]]
    if len(generated) != len(reference):
        raise RuntimeError(
            f"Reference mismatch for {name}: generated {len(generated)} bytes, "
            f"reference {len(reference)} bytes"
        )

    first = diffs[0]
    if page_base is None:
        bank = "LOW" if first < PAGE_SIZE else "HIGH"
        cpu = ROM_BASE + (first % PAGE_SIZE)
        where = f"physical {first:04X}H ({bank} CPU {cpu:04X}H)"
    else:
        where = f"CPU {page_base + first:04X}H"
    raise RuntimeError(
        f"Reference mismatch for {name}: {len(diffs)} differing bytes; first at {where}: "
        f"generated {generated[first]:02X}, reference {reference[first]:02X}"
    )


def write_outputs(build_dir: Path, low: bytes, high: bytes) -> None:
    combined = low + high
    if len(combined) != COMBINED_SIZE:
        raise AssertionError("Combined ROM image is not 8192 bytes")

    outputs = {
        LOW_NAME: low,
        HIGH_NAME: high,
        COMBINED_NAME: combined,
    }
    for name, data in outputs.items():
        (build_dir / name).write_bytes(data)

    hex_bytes = intel_hex(combined).encode("ascii")
    (build_dir / HEX_NAME).write_bytes(hex_bytes)

    sums = {
        LOW_NAME: sha256(low),
        HIGH_NAME: sha256(high),
        COMBINED_NAME: sha256(combined),
        HEX_NAME: sha256(hex_bytes),
    }
    (build_dir / SUMS_NAME).write_text(
        "".join(f"{digest}  {name}\n" for name, digest in sums.items()),
        encoding="ascii",
    )

    print(f"Built {build_dir / COMBINED_NAME}")
    print(f"  size:    {len(combined)} bytes")
    print(f"  SHA-256: {sums[COMBINED_NAME]}")


def verify_reference(build_dir: Path) -> None:
    generated_low = (build_dir / LOW_NAME).read_bytes()
    generated_high = (build_dir / HIGH_NAME).read_bytes()
    generated_combined = (build_dir / COMBINED_NAME).read_bytes()

    references = [
        (LOW_NAME, generated_low, ROM_BASE),
        (HIGH_NAME, generated_high, ROM_BASE),
        (COMBINED_NAME, generated_combined, None),
    ]
    for name, generated, page_base in references:
        path = ROOT / name
        if not path.exists():
            raise RuntimeError(f"Reference image not found: {path}")
        compare_reference(name, generated, path.read_bytes(), page_base)


def release_outputs(build_dir: Path) -> None:
    for name in (LOW_NAME, HIGH_NAME, COMBINED_NAME, HEX_NAME, SUMS_NAME):
        shutil.copy2(build_dir / name, ROOT / name)
    print("Updated checked-in release images from the assembled source build")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--assembler", default="z80asm", help="z80asm executable (default: z80asm)")
    parser.add_argument("--build-dir", default=str(ROOT / "build"), help="build output directory")
    parser.add_argument(
        "--verify-reference",
        action="store_true",
        help="require the assembled images to exactly match the checked-in release BINs",
    )
    parser.add_argument(
        "--release",
        action="store_true",
        help="copy generated BIN/HEX/SHA256SUMS files to the repository root",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    build_dir = Path(args.build_dir).resolve()
    build_dir.mkdir(parents=True, exist_ok=True)

    if not SOURCE.exists():
        raise RuntimeError(f"Source file not found: {SOURCE}")

    low = assemble_page(0, args.assembler, build_dir)
    high = assemble_page(1, args.assembler, build_dir)
    write_outputs(build_dir, low, high)

    if args.verify_reference:
        verify_reference(build_dir)
        print("Native assembler build exactly matches the checked-in V5.6 release images")

    if args.release:
        release_outputs(build_dir)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        raise SystemExit(1)
